# 1.Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np
null_vector=np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2.Create a vector with values ranging from 10 to 49.

In [4]:
import numpy as np
vector=np.arange(10,49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# 3.Create a 3x3 matrix with values ranging from 0 to 8.

In [7]:
import numpy as np
x=np.arange(0,9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4.Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
import numpy as np
arr=np.array([1,2,0,0,4,0])
a=np.nonzero(arr)
print(a)

(array([0, 1, 4], dtype=int64),)


# 5.Create a 10x10 array with random values and find the minimum and maximum values.

In [14]:
import numpy as np
x=np.random.random(size=(10,10))
min_val=np.amin(x)
max_val=np.amax(x)
print("Maximum Value:",max_val)
print("Minimum Value:",min_val)

Maximum Value: 0.9851396417661521
Minimum Value: 0.00666306025378649


# 6.Create a random vector of size 30 and find the mean value.

In [18]:
import numpy as np
x=np.random.random((30))
a=x.mean()
print(a)

0.4469947816233449
